[package]
name = "libutp-rs2"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
lazy_static = "1.5.0"
libutp-rs2-sys = { path = "../libutp-rs2-sys" }
os_socketaddr = "0.2.5"
parking_lot = "0.12.3"
tokio = { version = "1.43.0", features = ["net", "macros", "rt"] }
